CREATE TABLE IF NOT EXISTS AuthUsers (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, email TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS Users (id SERIAL PRIMARY KEY, name TEXT NOT NULL, experience_level TEXT NOT NULL, target_role TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Skills (id SERIAL PRIMARY KEY, skill_name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS RoleSkills (id SERIAL PRIMARY KEY, role TEXT NOT NULL, skill_name TEXT NOT NULL, importance TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS PasswordReset (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES AuthUsers(id), token TEXT UNIQUE NOT NULL, expires_at TIMESTAMP NOT NULL, used INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS UserSkills (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES Users(id), skill_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS Analysis (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES Users(id), match_percentage REAL NOT NULL, missing_skills TEXT NOT NULL, recommendations TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, result_json TEXT, keep_forever INTEGER DEFAULT 0, target_role TEXT);